//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryPocket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public double IDContract { get; set; }
        public Nullable<double> Account { get; set; }
        public Nullable<double> UserID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Period { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<double> Percet { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual User User { get; set; }
    }
}
