//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyInEveryPocket
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public double IDOperation { get; set; }
        public string NameOperation { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> NumberAccount { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
